repos:
  - repo: local
    hooks:
      - id: helm-lint
        name: Helm lint (all charts)
        language: script
        entry: scripts/helm-lint-all.sh
        pass_filenames: false
        files: ^charts/


  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
          - --document-dependency-values
