apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helmtemplates
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/rcbassil/helmtemplates.git
  ref:
    branch: main
